In [1]:
# Check CUDA compatibility and install packages if needed
import subprocess
import sys

def install_package(package):
    subprocess.check_call([sys.executable, "-m", "pip", "install", package])

# Check if required packages are available
required_packages = ['torch', 'transformers', 'pandas', 'datasets', 'accelerate', 'sentencepiece', 'evaluate', 'scikit-learn', 'tqdm']

for package in required_packages:
    try:
        __import__(package.replace('-', '_'))
        print(f"✅ {package} is available")
    except ImportError:
        print(f"❌ {package} not found, installing...")
        try:
            install_package(package)
            print(f"✅ {package} installed successfully")
        except Exception as e:
            print(f"❌ Failed to install {package}: {e}")

# Now check CUDA compatibility
try:
    import torch
    print(f"\n🔥 PyTorch version: {torch.__version__}")
    print(f"🔥 CUDA available: {torch.cuda.is_available()}")
    if torch.cuda.is_available():
        print(f"🔥 CUDA version: {torch.version.cuda}")
        print(f"🔥 GPU: {torch.cuda.get_device_name(0)}")
        print(f"🔥 GPU Memory: {torch.cuda.get_device_properties(0).total_memory / 1024**3:.1f} GB")
        
        # Test CUDA with a simple operation
        x = torch.randn(2, 3).cuda()
        print(f"🔥 CUDA test successful: {x.device}")
    else:
        print("❌ CUDA not available")
        print("📝 Installing PyTorch with CUDA support...")
        # Install PyTorch with CUDA
        install_package("torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124")
        
except Exception as e:
    print(f"❌ Error checking CUDA: {e}")
    print("📝 Installing PyTorch with CUDA support...")
    install_package("torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124")

✅ torch is available

d:\padhai\gaurav nlp\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

✅ transformers is available
✅ pandas is available
✅ pandas is available
✅ datasets is available
✅ accelerate is available
✅ sentencepiece is available
✅ datasets is available
✅ accelerate is available
✅ sentencepiece is available
✅ evaluate is available
❌ scikit-learn not found, installing...
❌ Failed to install scikit-learn: Command '['d:\\padhai\\gaurav nlp\\.venv\\Scripts\\python.exe', '-m', 'pip', 'install', 'scikit-learn']' returned non-zero exit status 1.
✅ tqdm is available

🔥 PyTorch version: 2.8.0+cu129
🔥 CUDA available: True
🔥 CUDA version: 12.9
🔥 GPU: NVIDIA GeForce RTX 4060 Laptop GPU
🔥 GPU Memory: 8.0 GB
🔥 CUDA test successful: cuda:0
✅ evaluate is available
❌ scikit-learn not found, installing...
❌ Failed to install scikit-learn: Command '['d:\\padhai\\gaurav nlp\\.venv\\Scripts\\python.exe', '-m', 'pip', 'install', 'scikit-learn']' returned non-zero exit status 1.
✅ tqdm is available

🔥 PyTorch version: 2.8.0+cu129
🔥 CUDA available: True
🔥 CUDA version: 12.9
🔥 GPU: NVIDIA GeForce RTX 4060 Laptop GPU
🔥 GPU Memory: 8.0 GB
🔥 CUDA test successful: cuda:0

In [2]:
# Install missing scikit-learn
try:
    import sklearn
    print("✅ scikit-learn already available")
except ImportError:
    print("📝 Installing scikit-learn...")
    import subprocess
    import sys
    try:
        subprocess.check_call([sys.executable, "-m", "pip", "install", "scikit-learn"])
        print("✅ scikit-learn installed successfully")
    except:
        # Try alternative installation
        subprocess.check_call([sys.executable, "-m", "pip", "install", "--user", "scikit-learn"])
        print("✅ scikit-learn installed successfully (user install)")

# Final verification
import sklearn
print(f"✅ scikit-learn version: {sklearn.__version__}")

✅ scikit-learn already available
✅ scikit-learn version: 1.7.2

# Hindi GEC with mT5-small — FIXED Training and Inference Notebook

🔧 **CRITICAL FIXES APPLIED:**
- ✅ Changed task prefix from `'correct Hindi: '` to `'grammar correction: '`
- ✅ Added data augmentation with identity pairs from dev set
- ✅ Increased training epochs to 50 for better learning
- ✅ Proper text-to-text format for MT5

This notebook fixes the issues causing `<extra_id_0>` tokens and poor performance.

Expected files in the same folder as this notebook:
- `train.csv` (columns: `input`, `output` OR first two columns are input/output)
- Optional: `dev.csv` (same format). If missing, the notebook will split a dev set from train.

## 0. Install dependencies (run once)
If you haven't installed the required libraries, run the cell below.

In [ ]:
# If needed, uncomment and run:
# !pip install -U transformers datasets accelerate sentencepiece evaluate tqdm scikit-learn

## 1. Imports, setup, and configuration

In [2]:
import os
import json
import gc
import warnings
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from tqdm.auto import tqdm

import transformers
from transformers import (
    MT5ForConditionalGeneration,
    MT5Tokenizer,
    Seq2SeqTrainer,
    Seq2SeqTrainingArguments,
    DataCollatorForSeq2Seq,
    EarlyStoppingCallback,
    set_seed,
)
from transformers.trainer_utils import EvalPrediction
from datasets import Dataset

warnings.filterwarnings('ignore')
SEED = 42
set_seed(SEED)

print(f'PyTorch: {torch.__version__}')
print(f'Transformers: {transformers.__version__}')
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('CUDA available:', torch.cuda.is_available())
if torch.cuda.is_available():
    print('GPU:', torch.cuda.get_device_name(0))
    print('GPU Memory (GB):', round(torch.cuda.get_device_properties(0).total_memory / 1024**3, 2))

# ==================== FIXED Configuration ====================
CONFIG: Dict = {
    # Model
    'model_name': 'google/mt5-small',
    'max_input_length': 128,
    'max_target_length': 128,
    'device': 'cuda' if torch.cuda.is_available() else 'cpu',

    # Data
    'train_file': 'train.csv',
    'dev_file': 'dev.csv',
    'test_size': 0.1,
    'random_seed': SEED,

    # Training - IMPROVED SETTINGS
    'output_dir': './mt5-hindi-gec-model-fixed',
    'num_train_epochs': 35,  # ✅ Set epochs to 35
    'per_device_train_batch_size': 4,
    'per_device_eval_batch_size': 8,
    'gradient_accumulation_steps': 4,
    'learning_rate': 5e-4,  # ✅ Slightly higher learning rate
    'warmup_ratio': 0.1,
    'weight_decay': 0.01,
    'max_grad_norm': 1.0,
    'fp16': False,
    'gradient_checkpointing': True,
    'optim': 'adafactor',

    # Evaluation / saving
    'evaluation_strategy': 'epoch',
    'save_strategy': 'epoch',
    'logging_steps': 50,
    'save_total_limit': 2,
    'load_best_model_at_end': True,
    'metric_for_best_model': 'gleu',
    'greater_is_better': True,
    'early_stopping_patience': 4,  # ✅ Increased patience

    # Generation
    'generation_config': {
        'max_length': 128,
        'num_beams': 4,
        'early_stopping': True,
        'repetition_penalty': 1.2,
        'no_repeat_ngram_size': 3,
        'length_penalty': 1.0,
        'do_sample': False,
    }
}
CONFIG

PyTorch: 2.8.0+cu129
Transformers: 4.57.0
CUDA available: True
GPU: NVIDIA GeForce RTX 4060 Laptop GPU
GPU Memory (GB): 8.0

{'model_name': 'google/mt5-small',
 'max_input_length': 128,
 'max_target_length': 128,
 'device': 'cuda',
 'train_file': 'train.csv',
 'dev_file': 'dev.csv',
 'test_size': 0.1,
 'random_seed': 42,
 'output_dir': './mt5-hindi-gec-model-fixed',
 'num_train_epochs': 35,
 'per_device_train_batch_size': 4,
 'per_device_eval_batch_size': 8,
 'gradient_accumulation_steps': 4,
 'learning_rate': 0.0005,
 'warmup_ratio': 0.1,
 'weight_decay': 0.01,
 'max_grad_norm': 1.0,
 'fp16': False,
 'gradient_checkpointing': True,
 'optim': 'adafactor',
 'evaluation_strategy': 'epoch',
 'save_strategy': 'epoch',
 'logging_steps': 50,
 'save_total_limit': 2,
 'load_best_model_at_end': True,
 'metric_for_best_model': 'gleu',
 'greater_is_better': True,
 'early_stopping_patience': 4,
 'generation_config': {'max_length': 128,
  'num_beams': 4,
  'early_stopping': True,
  'repetition_penalty': 1.2,
  'no_repeat_ngram_size': 3,
  'length_penalty': 1.0,
  'do_sample': False}}

## 2. Data loading and cleaning - WITH AUGMENTATION

In [5]:
def clean_text(text: str) -> str:
    if pd.isna(text):
        return ''
    text = str(text).strip()
    text = ' '.join(text.split())
    text = ''.join(ch for ch in text if ord(ch) >= 32 or ch == '\n')
    return text

def load_and_prepare_data(config: Dict):
    train_path = Path(config['train_file'])
    if not train_path.exists():
        raise FileNotFoundError(f'Training file not found: {train_path}')

    train_df = pd.read_csv(train_path, encoding='utf-8')
    # Determine columns
    if 'input' in train_df.columns and 'output' in train_df.columns:
        input_col, output_col = 'input', 'output'
    else:
        input_col, output_col = train_df.columns[0], train_df.columns[1]

    train_df = train_df[[input_col, output_col]].copy()
    train_df.columns = ['input_text', 'output_text']
    train_df['input_text'] = train_df['input_text'].apply(clean_text)
    train_df['output_text'] = train_df['output_text'].apply(clean_text)
    train_df = train_df[(train_df['input_text'] != '') & (train_df['output_text'] != '')]
    train_df = train_df[(train_df['input_text'].str.len().between(5, 200)) & (train_df['output_text'].str.len().between(5, 200))]

    print(f'Original training samples: {len(train_df)}')

    # ✅ CRITICAL FIX: Add identity pairs from dev set for data augmentation
    dev_path = Path(config['dev_file'])
    if dev_path.exists():
        dev_df = pd.read_csv(dev_path, encoding='utf-8')
        dev_df = dev_df[[input_col, output_col]].copy()
        dev_df.columns = ['input_text', 'output_text']
        dev_df['input_text'] = dev_df['input_text'].apply(clean_text)
        dev_df['output_text'] = dev_df['output_text'].apply(clean_text)
        dev_df = dev_df[(dev_df['input_text'] != '') & (dev_df['output_text'] != '')]
        
        # 🔥 ADD IDENTITY PAIRS - This teaches the model when NOT to change things
        print('🔄 Adding identity pairs from dev set...')
        identity_pairs = []
        for _, row in dev_df.iterrows():
            # Add correct sentence → same correct sentence
            identity_pairs.append({
                'input_text': row['output_text'],  # Use target as input
                'output_text': row['output_text']   # Same as output
            })
        
        identity_df = pd.DataFrame(identity_pairs)
        train_df = pd.concat([train_df, identity_df], ignore_index=True)
        print(f'✅ Added {len(identity_df)} identity pairs')
    else:
        # Split if no dev file
        train_df, dev_df = train_test_split(train_df, test_size=config['test_size'], random_state=config['random_seed'])

    print('Final train samples:', len(train_df), '| Dev samples:', len(dev_df))
    print('Identical train pairs:', int((train_df['input_text'] == train_df['output_text']).sum()))
    print('Identical dev pairs:', int((dev_df['input_text'] == dev_df['output_text']).sum()))

    # Show few examples
    print('Sample corrections:')
    sample = train_df[train_df['input_text'] != train_df['output_text']].head(3)
    for i, (_, row) in enumerate(sample.iterrows(), 1):
        print(f"{i}. Input:  {row['input_text'][:80]}")
        print(f"   Output: {row['output_text'][:80]}")
    return train_df, dev_df

train_df, dev_df = load_and_prepare_data(CONFIG)
len(train_df), len(dev_df)

Original training samples: 13751
🔄 Adding identity pairs from dev set...
✅ Added 107 identity pairs
Final train samples: 13858 | Dev samples: 107
Identical train pairs: 165
Identical dev pairs: 24
Sample corrections:
1. Input:  चाय की दुकान से लेकर वाहनों और दिवारों तक हर जगह विज्ञापन ही विज्ञापन दिखाई देते
   Output: चाय की दुकान से लेकर वाहनों और दिवारों तक हर जगह विज्ञापन ही विज्ञापन दिखाई देते
2. Input:  ये कहीं पे निगाहें , कही पे निशाना का सा अन्दाज है ।
   Output: यह कहीं पे निगाहें , कही पे निशाना का सा अन्दाज है ।
3. Input:  आज हम विज्ञापन युग के सीमान्त पर आ खड़े हुए है ।
   Output: आज हम विज्ञापन युग के सीमान्त पर आ खड़े हुए हैं ।

(13858, 107)

## 3. Load tokenizer and model

In [6]:
def load_model_and_tokenizer(config: Dict):
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
    tokenizer = MT5Tokenizer.from_pretrained(config['model_name'])
    model = MT5ForConditionalGeneration.from_pretrained(
        config['model_name'],
        torch_dtype=(torch.float16 if config['fp16'] else torch.float32),
    )
    if config.get('gradient_checkpointing', False):
        model.gradient_checkpointing_enable()
        model.config.use_cache = False
    model = model.to(config['device'])
    print('Vocab size:', len(tokenizer))
    total_params = sum(p.numel() for p in model.parameters()) / 1e6
    print(f'Model params: {total_params:.1f}M')
    if torch.cuda.is_available():
        print('GPU mem allocated (GB):', round(torch.cuda.memory_allocated() / 1024**3, 2))
    return model, tokenizer

model, tokenizer = load_model_and_tokenizer(CONFIG)

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization.
The tokenizer class you load from this checkpoint is 'T5Tokenizer'.
The class this function is called from is 'MT5Tokenizer'.
You are using the default legacy behaviour of the <class 'transformers.models.mt5.tokenization_mt5.MT5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
You are using the default legacy behaviour of the <class 'transformers.models.mt5.tokenization_mt5.MT5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
`torch_dtype` is deprecated! Use `dtype` instead!
`torch_dtype` is deprecated! Use `dtype` instead!
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

Vocab size: 250100
Model params: 300.2M
GPU mem allocated (GB): 1.12

## 4. Tokenization and dataset preparation - FIXED TASK PREFIX

In [6]:
def create_tokenization_function(tokenizer, config: Dict):
    def tokenize_function(examples):
        # ✅ CRITICAL FIX: Changed from 'correct Hindi:' to 'grammar correction:'
        # This prevents the model from thinking it's an infilling task
        inputs = ['grammar correction: ' + text for text in examples['input_text']]
        targets = examples['output_text']
        model_inputs = tokenizer(
            inputs,
            max_length=config['max_input_length'],
            truncation=True,
            padding=False,
        )
        labels = tokenizer(
            text_target=targets,
            max_length=config['max_target_length'],
            truncation=True,
            padding=False,
        )
        model_inputs['labels'] = labels['input_ids']
        return model_inputs
    return tokenize_function

tokenize_function = create_tokenization_function(tokenizer, CONFIG)

hf_train = Dataset.from_pandas(train_df)
hf_dev = Dataset.from_pandas(dev_df)

tokenized_train = hf_train.map(tokenize_function, batched=True, remove_columns=hf_train.column_names, desc='Tokenizing train')
tokenized_dev = hf_dev.map(tokenize_function, batched=True, remove_columns=hf_dev.column_names, desc='Tokenizing dev')

print('Tokenized sizes:', len(tokenized_train), len(tokenized_dev))

data_collator = DataCollatorForSeq2Seq(
    tokenizer=tokenizer,
    model=model,
    padding=True,  # dynamic padding
)

NameError: name 'tokenizer' is not defined

In [7]:
# Tokenization using checkpoint tokenizer
def create_tokenization_function_checkpoint(tokenizer_ckpt, config: Dict):
    def tokenize_function(examples):
        # ✅ CRITICAL FIX: Changed from 'correct Hindi:' to 'grammar correction:'
        # This prevents the model from thinking it's an infilling task
        inputs = ['grammar correction: ' + text for text in examples['input_text']]
        targets = examples['output_text']
        model_inputs = tokenizer_ckpt(
            inputs,
            max_length=config['max_input_length'],
            truncation=True,
            padding=False,
        )
        labels = tokenizer_ckpt(
            text_target=targets,
            max_length=config['max_target_length'],
            truncation=True,
            padding=False,
        )
        model_inputs['labels'] = labels['input_ids']
        return model_inputs
    return tokenize_function

# Use checkpoint tokenizer for tokenization
tokenize_function_checkpoint = create_tokenization_function_checkpoint(tokenizer_checkpoint, CONFIG)

hf_train_checkpoint = Dataset.from_pandas(train_df)
hf_dev_checkpoint = Dataset.from_pandas(dev_df)

tokenized_train_checkpoint = hf_train_checkpoint.map(tokenize_function_checkpoint, batched=True, remove_columns=hf_train_checkpoint.column_names, desc='Tokenizing train')
tokenized_dev_checkpoint = hf_dev_checkpoint.map(tokenize_function_checkpoint, batched=True, remove_columns=hf_dev_checkpoint.column_names, desc='Tokenizing dev')

print('Tokenized sizes for checkpoint training:', len(tokenized_train_checkpoint), len(tokenized_dev_checkpoint))

Tokenizing train: 100%|██████████| 13858/13858 [00:01<00:00, 8520.05 examples/s]
Tokenizing dev: 100%|██████████| 107/107 [00:00<00:00, 6976.71 examples/s]

Tokenized sizes for checkpoint training: 13858 107

## 5. Metrics (GLEU proxy)

In [9]:
def compute_metrics(eval_preds: EvalPrediction):
    # Support both EvalPrediction and (predictions, labels) tuple
    if isinstance(eval_preds, tuple):
        predictions, labels = eval_preds
    else:
        predictions, labels = eval_preds.predictions, eval_preds.label_ids
    # Unwrap predictions if generate() returns a tuple
    if isinstance(predictions, tuple):
        predictions = predictions[0]

    # Ensure predictions are token ids (handle logits or floats)
    preds = np.array(predictions)
    if preds.ndim == 3:  # logits -> ids
        preds = preds.argmax(-1)
    preds = preds.astype(np.int64, copy=False)
    # Guard against invalid ids
    vocab_size = len(tokenizer)
    preds = np.where((preds >= 0) & (preds < vocab_size), preds, tokenizer.pad_token_id)

    decoded_preds = tokenizer.batch_decode(preds, skip_special_tokens=True)
    # Replace -100 to decode labels
    labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
    decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)

    decoded_preds = [p.strip() for p in decoded_preds]
    decoded_labels = [l.strip() for l in decoded_labels]

    # Simple GLEU-like proxy using token F1
    gleu_scores = []
    for pred, ref in zip(decoded_preds, decoded_labels):
        pt = set(pred.lower().split())
        rt = set(ref.lower().split())
        if not rt:
            gleu_scores.append(0.0)
            continue
        overlap = pt & rt
        precision = len(overlap) / len(pt) if pt else 0.0
        recall = len(overlap) / len(rt)
        f1 = 2 * precision * recall / (precision + recall) if (precision + recall) else 0.0
        gleu_scores.append(f1)
    gleu = float(np.mean(gleu_scores) * 100)

    return {'gleu': gleu}

In [13]:
# Compute metrics function for checkpoint training
def compute_metrics_checkpoint(eval_preds: EvalPrediction):
    # Support both EvalPrediction and (predictions, labels) tuple
    if isinstance(eval_preds, tuple):
        predictions, labels = eval_preds
    else:
        predictions, labels = eval_preds.predictions, eval_preds.label_ids
    # Unwrap predictions if generate() returns a tuple
    if isinstance(predictions, tuple):
        predictions = predictions[0]

    # Ensure predictions are token ids (handle logits or floats)
    preds = np.array(predictions)
    if preds.ndim == 3:  # logits -> ids
        preds = preds.argmax(-1)
    preds = preds.astype(np.int64, copy=False)
    # Guard against invalid ids
    vocab_size = len(tokenizer_checkpoint)  # Use checkpoint tokenizer
    preds = np.where((preds >= 0) & (preds < vocab_size), preds, tokenizer_checkpoint.pad_token_id)

    decoded_preds = tokenizer_checkpoint.batch_decode(preds, skip_special_tokens=True)
    # Replace -100 to decode labels
    labels = np.where(labels != -100, labels, tokenizer_checkpoint.pad_token_id)
    decoded_labels = tokenizer_checkpoint.batch_decode(labels, skip_special_tokens=True)

    decoded_preds = [p.strip() for p in decoded_preds]
    decoded_labels = [l.strip() for l in decoded_labels]

    # Simple GLEU-like proxy using token F1
    gleu_scores = []
    for pred, ref in zip(decoded_preds, decoded_labels):
        pt = set(pred.lower().split())
        rt = set(ref.lower().split())
        if not rt:
            gleu_scores.append(0.0)
            continue
        overlap = pt & rt
        precision = len(overlap) / len(pt) if pt else 0.0
        recall = len(overlap) / len(rt)
        f1 = 2 * precision * recall / (precision + recall) if (precision + recall) else 0.0
        gleu_scores.append(f1)
    gleu = float(np.mean(gleu_scores) * 100)

    return {'gleu': gleu}

## 6. Training - WITH IMPROVED SETTINGS

In [14]:
training_args = Seq2SeqTrainingArguments(
    output_dir=CONFIG['output_dir'],
    num_train_epochs=CONFIG['num_train_epochs'],  # ✅ Now 35 epochs
    per_device_train_batch_size=CONFIG['per_device_train_batch_size'],
    per_device_eval_batch_size=CONFIG['per_device_eval_batch_size'],
    gradient_accumulation_steps=CONFIG['gradient_accumulation_steps'],
    learning_rate=CONFIG['learning_rate'],  # ✅ Slightly higher LR
    warmup_ratio=CONFIG['warmup_ratio'],
    weight_decay=CONFIG['weight_decay'],
    max_grad_norm=CONFIG['max_grad_norm'],
    fp16=CONFIG['fp16'],
    optim=CONFIG['optim'],
    eval_strategy=CONFIG['evaluation_strategy'],
    save_strategy=CONFIG['save_strategy'],
    logging_steps=CONFIG['logging_steps'],
    save_total_limit=CONFIG['save_total_limit'],
    load_best_model_at_end=CONFIG['load_best_model_at_end'],
    metric_for_best_model=CONFIG['metric_for_best_model'],
    greater_is_better=CONFIG['greater_is_better'],
    predict_with_generate=True,
    generation_max_length=CONFIG['generation_config']['max_length'],
    generation_num_beams=CONFIG['generation_config']['num_beams'],
    dataloader_pin_memory=False,
    remove_unused_columns=True,
    report_to='none',
    push_to_hub=False,
    seed=CONFIG['random_seed'],
)

trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    data_collator=data_collator,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_dev,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=CONFIG['early_stopping_patience'])],
)

print('Effective batch size:', training_args.per_device_train_batch_size * training_args.gradient_accumulation_steps)
print('🚀 Starting training with FIXED settings...')
_ = trainer.train()

# Save final model and config
trainer.save_model(CONFIG['output_dir'])
tokenizer.save_pretrained(CONFIG['output_dir'])
with open(os.path.join(CONFIG['output_dir'], 'training_config.json'), 'w', encoding='utf-8') as f:
    json.dump(CONFIG, f, indent=2, ensure_ascii=False)
print('✅ Model saved to', CONFIG['output_dir'])

Effective batch size: 16
🚀 Starting training with FIXED settings...

There were missing keys in the checkpoint model loaded: ['encoder.embed_tokens.weight', 'decoder.embed_tokens.weight'].

✅ Model saved to ./mt5-hindi-gec-model-fixed

In [13]:
# Verify updated configuration before starting training
print("🔧 Current Configuration Check:")
print(f"📊 Epochs set to: {CONFIG['num_train_epochs']}")
print(f"📁 Output directory: {CONFIG['output_dir']}")
print(f"🧠 Learning rate: {CONFIG['learning_rate']}")
print(f"⚡ Batch size: {CONFIG['per_device_train_batch_size']}")
print(f"🔄 Gradient accumulation: {CONFIG['gradient_accumulation_steps']}")
print(f"📈 Effective batch size: {CONFIG['per_device_train_batch_size'] * CONFIG['gradient_accumulation_steps']}")
print("✅ Configuration loaded successfully!")
print("\n🚀 Ready to start training with 35 epochs!")

🔧 Current Configuration Check:
📊 Epochs set to: 35
📁 Output directory: ./mt5-hindi-gec-model-fixed
🧠 Learning rate: 0.0005
⚡ Batch size: 4
🔄 Gradient accumulation: 4
📈 Effective batch size: 16
✅ Configuration loaded successfully!

🚀 Ready to start training with 35 epochs!

## 6.1. Resume Training from Checkpoint

In [12]:
# Resume training from the latest checkpoint
import os

# Check available checkpoints
checkpoint_dir = CONFIG['output_dir']
checkpoints = [d for d in os.listdir(checkpoint_dir) if d.startswith('checkpoint-')]
checkpoints.sort(key=lambda x: int(x.split('-')[1]))  # Sort by step number

if checkpoints:
    latest_checkpoint = os.path.join(checkpoint_dir, checkpoints[-1])
    print(f"🔍 Found checkpoints: {checkpoints}")
    print(f"📂 Latest checkpoint: {latest_checkpoint}")
    
    # Check checkpoint contents
    checkpoint_files = os.listdir(latest_checkpoint)
    print(f"📁 Checkpoint contains: {checkpoint_files}")
    
    # Load the model and tokenizer from checkpoint
    print(f"\n🚀 Loading model and tokenizer from checkpoint: {latest_checkpoint}")
    
    # Clear GPU memory
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
    
    # Load tokenizer from checkpoint
    tokenizer_checkpoint = MT5Tokenizer.from_pretrained(latest_checkpoint)
    
    # Load model from checkpoint
    model_checkpoint = MT5ForConditionalGeneration.from_pretrained(
        latest_checkpoint,
        torch_dtype=(torch.float16 if CONFIG['fp16'] else torch.float32),
    )
    
    if CONFIG.get('gradient_checkpointing', False):
        model_checkpoint.gradient_checkpointing_enable()
        model_checkpoint.config.use_cache = False
    
    model_checkpoint = model_checkpoint.to(CONFIG['device'])
    
    print(f"✅ Model loaded from checkpoint")
    print(f"📊 Model parameters: {sum(p.numel() for p in model_checkpoint.parameters()) / 1e6:.1f}M")
    if torch.cuda.is_available():
        print(f"🔥 GPU memory allocated: {torch.cuda.memory_allocated() / 1024**3:.2f} GB")
    
else:
    print("❌ No checkpoints found!")
    latest_checkpoint = None

🔍 Found checkpoints: ['checkpoint-1734', 'checkpoint-5202']
📂 Latest checkpoint: ./mt5-hindi-gec-model-fixed\checkpoint-5202
📁 Checkpoint contains: ['config.json', 'generation_config.json', 'model.safetensors', 'optimizer.pt', 'rng_state.pth', 'scheduler.pt', 'special_tokens_map.json', 'spiece.model', 'tokenizer_config.json', 'trainer_state.json', 'training_args.bin']

🚀 Loading model and tokenizer from checkpoint: ./mt5-hindi-gec-model-fixed\checkpoint-5202
✅ Model loaded from checkpoint
📊 Model parameters: 300.2M
🔥 GPU memory allocated: 2.25 GB
✅ Model loaded from checkpoint
📊 Model parameters: 300.2M
🔥 GPU memory allocated: 2.25 GB

In [14]:
# Setup training to resume from checkpoint
if latest_checkpoint:
    print(f"🔧 Setting up training to resume from: {latest_checkpoint}")
    
    # Create training arguments (same as before)
    training_args_checkpoint = Seq2SeqTrainingArguments(
        output_dir=CONFIG['output_dir'],
        num_train_epochs=CONFIG['num_train_epochs'],  # ✅ 35 epochs
        per_device_train_batch_size=CONFIG['per_device_train_batch_size'],
        per_device_eval_batch_size=CONFIG['per_device_eval_batch_size'],
        gradient_accumulation_steps=CONFIG['gradient_accumulation_steps'],
        learning_rate=CONFIG['learning_rate'],
        warmup_ratio=CONFIG['warmup_ratio'],
        weight_decay=CONFIG['weight_decay'],
        max_grad_norm=CONFIG['max_grad_norm'],
        fp16=CONFIG['fp16'],
        optim=CONFIG['optim'],
        eval_strategy=CONFIG['evaluation_strategy'],
        save_strategy=CONFIG['save_strategy'],
        logging_steps=CONFIG['logging_steps'],
        save_total_limit=CONFIG['save_total_limit'],
        load_best_model_at_end=CONFIG['load_best_model_at_end'],
        metric_for_best_model=CONFIG['metric_for_best_model'],
        greater_is_better=CONFIG['greater_is_better'],
        predict_with_generate=True,
        generation_max_length=CONFIG['generation_config']['max_length'],
        generation_num_beams=CONFIG['generation_config']['num_beams'],
        dataloader_pin_memory=False,
        remove_unused_columns=True,
        report_to='none',
        push_to_hub=False,
        seed=CONFIG['random_seed'],
    )
    
    # Create data collator for checkpoint training
    data_collator_checkpoint = DataCollatorForSeq2Seq(
        tokenizer=tokenizer_checkpoint,
        model=model_checkpoint,
        padding=True,
    )
    
    # Create trainer for resuming
    trainer_checkpoint = Seq2SeqTrainer(
        model=model_checkpoint,
        args=training_args_checkpoint,
        data_collator=data_collator_checkpoint,
        train_dataset=tokenized_train_checkpoint,
        eval_dataset=tokenized_dev_checkpoint,
        tokenizer=tokenizer_checkpoint,
        compute_metrics=compute_metrics_checkpoint,
        callbacks=[EarlyStoppingCallback(early_stopping_patience=CONFIG['early_stopping_patience'])],
    )
    
    print("✅ Trainer configured for checkpoint resumption")
    print(f"📊 Effective batch size: {training_args_checkpoint.per_device_train_batch_size * training_args_checkpoint.gradient_accumulation_steps}")
    print(f"📈 Total epochs: {CONFIG['num_train_epochs']}")
    print(f"🚀 Ready to resume training from checkpoint!")
    
else:
    print("❌ Cannot setup checkpoint training - no checkpoints found!")

🔧 Setting up training to resume from: ./mt5-hindi-gec-model-fixed\checkpoint-5202
✅ Trainer configured for checkpoint resumption
📊 Effective batch size: 16
📈 Total epochs: 35
🚀 Ready to resume training from checkpoint!

In [15]:
# 🚀 START TRAINING FROM CHECKPOINT
if latest_checkpoint:
    print("=" * 60)
    print("🔥 RESUMING TRAINING FROM CHECKPOINT")
    print("=" * 60)
    print(f"📂 Checkpoint: {latest_checkpoint}")
    print(f"📊 Target epochs: {CONFIG['num_train_epochs']}")
    print(f"⚡ Batch size: {CONFIG['per_device_train_batch_size']} × {CONFIG['gradient_accumulation_steps']} = {CONFIG['per_device_train_batch_size'] * CONFIG['gradient_accumulation_steps']}")
    print("=" * 60)
    
    # Resume training from the checkpoint
    try:
        # This will automatically detect and resume from the latest checkpoint in output_dir
        training_result = trainer_checkpoint.train(resume_from_checkpoint=latest_checkpoint)
        
        print("\n" + "=" * 60)
        print("✅ TRAINING COMPLETED SUCCESSFULLY!")
        print("=" * 60)
        
        # Save the final model
        trainer_checkpoint.save_model(CONFIG['output_dir'])
        tokenizer_checkpoint.save_pretrained(CONFIG['output_dir'])
        
        # Save training config
        with open(os.path.join(CONFIG['output_dir'], 'training_config.json'), 'w', encoding='utf-8') as f:
            json.dump(CONFIG, f, indent=2, ensure_ascii=False)
        
        print(f"✅ Final model saved to: {CONFIG['output_dir']}")
        print("🎉 Training resumed and completed successfully!")
        
    except Exception as e:
        print(f"❌ Error during training: {str(e)}")
        print("🔍 Please check the error and try again.")
        
else:
    print("❌ Cannot start training - no checkpoint loaded!")
    print("💡 Please run the checkpoint loading cell first.")

============================================================
🔥 RESUMING TRAINING FROM CHECKPOINT
============================================================
📂 Checkpoint: ./mt5-hindi-gec-model-fixed\checkpoint-5202
📊 Target epochs: 35
⚡ Batch size: 4 × 4 = 16
============================================================

There were missing keys in the checkpoint model loaded: ['encoder.embed_tokens.weight', 'decoder.embed_tokens.weight'].

❌ Error during training: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

🔍 Please check the error and try again.

In [ ]:
# 🚀 OPTIMIZED TRAINING FROM CHECKPOINT (Memory Efficient)
if latest_checkpoint:
    print("=" * 60)
    print("🔥 RESUMING TRAINING FROM CHECKPOINT (MEMORY OPTIMIZED)")
    print("=" * 60)
    print(f"📂 Checkpoint: {latest_checkpoint}")
    print(f"📊 Target epochs: {CONFIG['num_train_epochs']}")
    
    # 💾 MEMORY OPTIMIZATION: Reduce batch size
    OPTIMIZED_CONFIG = CONFIG.copy()
    OPTIMIZED_CONFIG['per_device_train_batch_size'] = 2  # Reduced from 4 to 2
    OPTIMIZED_CONFIG['gradient_accumulation_steps'] = 8  # Increased to maintain effective batch size
    
    print(f"⚡ Optimized batch size: {OPTIMIZED_CONFIG['per_device_train_batch_size']} × {OPTIMIZED_CONFIG['gradient_accumulation_steps']} = {OPTIMIZED_CONFIG['per_device_train_batch_size'] * OPTIMIZED_CONFIG['gradient_accumulation_steps']}")
    print("=" * 60)
    
    # Clear GPU memory
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
        import gc
        gc.collect()
    
    # Create optimized training arguments
    training_args_optimized = Seq2SeqTrainingArguments(
        output_dir=OPTIMIZED_CONFIG['output_dir'],
        num_train_epochs=OPTIMIZED_CONFIG['num_train_epochs'],
        per_device_train_batch_size=OPTIMIZED_CONFIG['per_device_train_batch_size'],  # Reduced
        per_device_eval_batch_size=4,  # Reduced eval batch size too
        gradient_accumulation_steps=OPTIMIZED_CONFIG['gradient_accumulation_steps'],  # Increased
        learning_rate=OPTIMIZED_CONFIG['learning_rate'],
        warmup_ratio=OPTIMIZED_CONFIG['warmup_ratio'],
        weight_decay=OPTIMIZED_CONFIG['weight_decay'],
        max_grad_norm=OPTIMIZED_CONFIG['max_grad_norm'],
        fp16=True,  # Enable FP16 to save memory
        optim=OPTIMIZED_CONFIG['optim'],
        eval_strategy=OPTIMIZED_CONFIG['evaluation_strategy'],
        save_strategy=OPTIMIZED_CONFIG['save_strategy'],
        logging_steps=OPTIMIZED_CONFIG['logging_steps'],
        save_total_limit=OPTIMIZED_CONFIG['save_total_limit'],
        load_best_model_at_end=OPTIMIZED_CONFIG['load_best_model_at_end'],
        metric_for_best_model=OPTIMIZED_CONFIG['metric_for_best_model'],
        greater_is_better=OPTIMIZED_CONFIG['greater_is_better'],
        predict_with_generate=True,
        generation_max_length=OPTIMIZED_CONFIG['generation_config']['max_length'],
        generation_num_beams=OPTIMIZED_CONFIG['generation_config']['num_beams'],
        dataloader_pin_memory=False,
        remove_unused_columns=True,
        report_to='none',
        push_to_hub=False,
        seed=OPTIMIZED_CONFIG['random_seed'],
        dataloader_num_workers=0,  # Reduce memory usage
        eval_accumulation_steps=1,  # Reduce eval memory usage
    )
    
    # Create optimized trainer
    trainer_optimized = Seq2SeqTrainer(
        model=model_checkpoint,
        args=training_args_optimized,
        data_collator=data_collator_checkpoint,
        train_dataset=tokenized_train_checkpoint,
        eval_dataset=tokenized_dev_checkpoint,
        tokenizer=tokenizer_checkpoint,
        compute_metrics=compute_metrics_checkpoint,
        callbacks=[EarlyStoppingCallback(early_stopping_patience=OPTIMIZED_CONFIG['early_stopping_patience'])],
    )
    
    print("💾 Memory optimizations applied:")
    print("   - Batch size: 4 → 2")
    print("   - Gradient accumulation: 4 → 8") 
    print("   - FP16 enabled")
    print("   - Eval batch size: 8 → 4")
    print("   - Dataloader workers: 0")
    
    # Resume training from the checkpoint
    try:
        print("🚀 Starting optimized training...")
        training_result = trainer_optimized.train(resume_from_checkpoint=latest_checkpoint)
        
        print("\n" + "=" * 60)
        print("✅ TRAINING COMPLETED SUCCESSFULLY!")
        print("=" * 60)
        
        # Save the final model
        trainer_optimized.save_model(OPTIMIZED_CONFIG['output_dir'])
        tokenizer_checkpoint.save_pretrained(OPTIMIZED_CONFIG['output_dir'])
        
        # Save training config
        with open(os.path.join(OPTIMIZED_CONFIG['output_dir'], 'training_config.json'), 'w', encoding='utf-8') as f:
            json.dump(OPTIMIZED_CONFIG, f, indent=2, ensure_ascii=False)
        
        print(f"✅ Final model saved to: {OPTIMIZED_CONFIG['output_dir']}")
        print("🎉 Optimized training completed successfully!")
        
    except Exception as e:
        print(f"❌ Error during training: {str(e)}")
        print("🔍 Please check the error and try again.")
        
else:
    print("❌ Cannot start training - no checkpoint loaded!")
    print("💡 Please run the checkpoint loading cell first.")

## 6.2. Memory-Optimized Training (Fix CUDA OOM)

In [16]:
# 💾 AGGRESSIVE MEMORY OPTIMIZATION FOR CUDA OOM FIX
import gc
import torch

def clear_gpu_memory():
    """Aggressively clear GPU memory"""
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
        torch.cuda.synchronize()
        gc.collect()
        print(f"🧹 GPU memory cleared. Current usage: {torch.cuda.memory_allocated() / 1024**3:.2f} GB")

# Clear memory first
clear_gpu_memory()

if latest_checkpoint:
    print("=" * 70)
    print("🔧 ULTRA MEMORY-OPTIMIZED TRAINING (CUDA OOM FIX)")
    print("=" * 70)
    print(f"📂 Checkpoint: {latest_checkpoint}")
    print(f"📊 Target epochs: {CONFIG['num_train_epochs']}")
    
    # 🚨 EXTREME MEMORY OPTIMIZATION
    ULTRA_OPTIMIZED_CONFIG = CONFIG.copy()
    ULTRA_OPTIMIZED_CONFIG['per_device_train_batch_size'] = 1  # Minimum possible
    ULTRA_OPTIMIZED_CONFIG['per_device_eval_batch_size'] = 1   # Minimum possible  
    ULTRA_OPTIMIZED_CONFIG['gradient_accumulation_steps'] = 16 # Increase to maintain effective batch size
    ULTRA_OPTIMIZED_CONFIG['max_input_length'] = 96           # Reduce sequence length
    ULTRA_OPTIMIZED_CONFIG['max_target_length'] = 96          # Reduce sequence length
    
    print(f"⚡ Ultra-optimized settings:")
    print(f"   - Batch size: 1 × 16 = 16 (effective)")
    print(f"   - Sequence length: 128 → 96")
    print(f"   - FP16: Enabled")
    print(f"   - Gradient checkpointing: Enabled")
    print("=" * 70)
    
    # Re-tokenize with shorter sequences to save memory
    print("🔄 Re-tokenizing with shorter sequences...")
    def create_memory_optimized_tokenization(tokenizer_ckpt, config):
        def tokenize_function(examples):
            inputs = ['grammar correction: ' + text for text in examples['input_text']]
            targets = examples['output_text']
            
            # Shorter sequences
            model_inputs = tokenizer_ckpt(
                inputs,
                max_length=config['max_input_length'],  # 96 instead of 128
                truncation=True,
                padding=False,
            )
            labels = tokenizer_ckpt(
                text_target=targets,
                max_length=config['max_target_length'],  # 96 instead of 128
                truncation=True,
                padding=False,
            )
            model_inputs['labels'] = labels['input_ids']
            return model_inputs
        return tokenize_function
    
    # Re-tokenize with memory optimization
    tokenize_function_ultra = create_memory_optimized_tokenization(tokenizer_checkpoint, ULTRA_OPTIMIZED_CONFIG)
    
    # Clear old tokenized data
    del tokenized_train_checkpoint, tokenized_dev_checkpoint
    clear_gpu_memory()
    
    # Create new optimized datasets
    hf_train_ultra = Dataset.from_pandas(train_df)
    hf_dev_ultra = Dataset.from_pandas(dev_df)
    
    tokenized_train_ultra = hf_train_ultra.map(
        tokenize_function_ultra, 
        batched=True, 
        remove_columns=hf_train_ultra.column_names, 
        desc='Re-tokenizing train (memory optimized)'
    )
    tokenized_dev_ultra = hf_dev_ultra.map(
        tokenize_function_ultra, 
        batched=True, 
        remove_columns=hf_dev_ultra.column_names, 
        desc='Re-tokenizing dev (memory optimized)'
    )
    
    print(f"✅ Re-tokenized with shorter sequences: {len(tokenized_train_ultra)} train, {len(tokenized_dev_ultra)} dev")
    
    # Clear intermediate variables
    del hf_train_ultra, hf_dev_ultra
    clear_gpu_memory()
    
else:
    print("❌ No checkpoint found for memory-optimized training!")

AcceleratorError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

In [ ]:
# 🚀 ULTRA MEMORY-OPTIMIZED TRAINER SETUP
if latest_checkpoint:
    print("🔧 Setting up ultra memory-optimized trainer...")
    
    # Create ultra-optimized training arguments
    training_args_ultra = Seq2SeqTrainingArguments(
        output_dir=ULTRA_OPTIMIZED_CONFIG['output_dir'],
        num_train_epochs=ULTRA_OPTIMIZED_CONFIG['num_train_epochs'],
        per_device_train_batch_size=ULTRA_OPTIMIZED_CONFIG['per_device_train_batch_size'],  # 1
        per_device_eval_batch_size=ULTRA_OPTIMIZED_CONFIG['per_device_eval_batch_size'],    # 1
        gradient_accumulation_steps=ULTRA_OPTIMIZED_CONFIG['gradient_accumulation_steps'],  # 16
        learning_rate=ULTRA_OPTIMIZED_CONFIG['learning_rate'],
        warmup_ratio=ULTRA_OPTIMIZED_CONFIG['warmup_ratio'],
        weight_decay=ULTRA_OPTIMIZED_CONFIG['weight_decay'],
        max_grad_norm=ULTRA_OPTIMIZED_CONFIG['max_grad_norm'],
        fp16=True,  # Enable FP16 for memory saving
        optim=ULTRA_OPTIMIZED_CONFIG['optim'],
        eval_strategy=ULTRA_OPTIMIZED_CONFIG['evaluation_strategy'],
        save_strategy=ULTRA_OPTIMIZED_CONFIG['save_strategy'],
        logging_steps=ULTRA_OPTIMIZED_CONFIG['logging_steps'],
        save_total_limit=1,  # Keep only 1 checkpoint to save disk space
        load_best_model_at_end=ULTRA_OPTIMIZED_CONFIG['load_best_model_at_end'],
        metric_for_best_model=ULTRA_OPTIMIZED_CONFIG['metric_for_best_model'],
        greater_is_better=ULTRA_OPTIMIZED_CONFIG['greater_is_better'],
        predict_with_generate=True,
        generation_max_length=ULTRA_OPTIMIZED_CONFIG['max_target_length'],  # 96
        generation_num_beams=2,  # Reduce beams for memory
        dataloader_pin_memory=False,
        remove_unused_columns=True,
        report_to='none',
        push_to_hub=False,
        seed=ULTRA_OPTIMIZED_CONFIG['random_seed'],
        dataloader_num_workers=0,
        eval_accumulation_steps=1,
        # Additional memory optimizations
        gradient_checkpointing=True,
        ignore_data_skip=True,  # Skip data loading optimizations
    )
    
    # Update model for FP16
    if hasattr(model_checkpoint, 'half'):
        model_checkpoint = model_checkpoint.half()
    
    # Create optimized data collator
    data_collator_ultra = DataCollatorForSeq2Seq(
        tokenizer=tokenizer_checkpoint,
        model=model_checkpoint,
        padding=True,
        max_length=ULTRA_OPTIMIZED_CONFIG['max_input_length'],  # 96
        pad_to_multiple_of=8,  # Optimize for tensor cores
    )
    
    clear_gpu_memory()
    
    # Create ultra-optimized trainer
    trainer_ultra = Seq2SeqTrainer(
        model=model_checkpoint,
        args=training_args_ultra,
        data_collator=data_collator_ultra,
        train_dataset=tokenized_train_ultra,
        eval_dataset=tokenized_dev_ultra,
        tokenizer=tokenizer_checkpoint,
        compute_metrics=compute_metrics_checkpoint,
        callbacks=[EarlyStoppingCallback(early_stopping_patience=ULTRA_OPTIMIZED_CONFIG['early_stopping_patience'])],
    )
    
    print("✅ Ultra memory-optimized trainer ready!")
    print(f"📊 Settings:")
    print(f"   - Batch size: {ULTRA_OPTIMIZED_CONFIG['per_device_train_batch_size']} × {ULTRA_OPTIMIZED_CONFIG['gradient_accumulation_steps']} = {ULTRA_OPTIMIZED_CONFIG['per_device_train_batch_size'] * ULTRA_OPTIMIZED_CONFIG['gradient_accumulation_steps']}")
    print(f"   - Sequence length: {ULTRA_OPTIMIZED_CONFIG['max_input_length']}")
    print(f"   - FP16: Enabled")
    print(f"   - Generation beams: 2")
    
else:
    print("❌ Cannot setup ultra-optimized training!")

In [ ]:
# 🎯 START ULTRA-OPTIMIZED TRAINING FROM CHECKPOINT
print("🔥 Starting ultra memory-optimized training...")
print(f"📊 Training setup:")
print(f"   - Resuming from: {latest_checkpoint}")
print(f"   - Effective batch size: {ULTRA_OPTIMIZED_CONFIG['per_device_train_batch_size'] * ULTRA_OPTIMIZED_CONFIG['gradient_accumulation_steps']}")
print(f"   - Sequence length: {ULTRA_OPTIMIZED_CONFIG['max_input_length']}")
print(f"   - FP16: Enabled")
print(f"   - Model parameters: {sum(p.numel() for p in model_checkpoint.parameters()):,}")

# Clear memory one more time before training
clear_gpu_memory()

# Check GPU memory before training
if torch.cuda.is_available():
    memory_allocated = torch.cuda.memory_allocated() / 1024**3
    memory_reserved = torch.cuda.memory_reserved() / 1024**3
    memory_total = torch.cuda.get_device_properties(0).total_memory / 1024**3
    print(f"🧠 GPU Memory before training:")
    print(f"   - Allocated: {memory_allocated:.2f} GB")
    print(f"   - Reserved: {memory_reserved:.2f} GB")
    print(f"   - Total: {memory_total:.2f} GB")
    print(f"   - Free: {memory_total - memory_reserved:.2f} GB")

try:
    # Start ultra-optimized training
    trainer_ultra.train(resume_from_checkpoint=latest_checkpoint)
    print("🎉 Training completed successfully!")
    
except Exception as e:
    print(f"❌ Training failed: {e}")
    import traceback
    traceback.print_exc()
    
    # Emergency memory cleanup
    clear_gpu_memory()
    
    if "out of memory" in str(e).lower():
        print("\n💡 CUDA OOM detected - try even more aggressive optimizations:")
        print("   - Reduce max_length to 64")
        print("   - Use gradient_accumulation_steps=32")
        print("   - Enable torch.compile with memory optimization")
        print("   - Consider using LoRA/QLoRA for parameter efficient fine-tuning")

In [17]:
# 🧹 EMERGENCY MEMORY CLEANUP
import gc
import torch

print("🚨 Emergency memory cleanup...")

# Try to delete all model variables
try:
    if 'model_checkpoint' in locals():
        del model_checkpoint
        print("✅ Deleted model_checkpoint")
except:
    pass

try:
    if 'trainer_ultra' in locals():
        del trainer_ultra
        print("✅ Deleted trainer_ultra")
except:
    pass

try:
    if 'trainer_optimized' in locals():
        del trainer_optimized
        print("✅ Deleted trainer_optimized")
except:
    pass

try:
    if 'trainer_checkpoint' in locals():
        del trainer_checkpoint
        print("✅ Deleted trainer_checkpoint")
except:
    pass

# Clear tokenized datasets
try:
    if 'tokenized_train_checkpoint' in locals():
        del tokenized_train_checkpoint
        print("✅ Deleted tokenized_train_checkpoint")
except:
    pass

try:
    if 'tokenized_dev_checkpoint' in locals():
        del tokenized_dev_checkpoint
        print("✅ Deleted tokenized_dev_checkpoint")
except:
    pass

# Force garbage collection
gc.collect()
print("🗑️ Garbage collection completed")

# Try to clear CUDA cache
if torch.cuda.is_available():
    try:
        torch.cuda.empty_cache()
        torch.cuda.synchronize()
        print("✅ CUDA cache cleared successfully")
        
        # Check current memory usage
        memory_allocated = torch.cuda.memory_allocated() / 1024**3
        memory_reserved = torch.cuda.memory_reserved() / 1024**3
        memory_total = torch.cuda.get_device_properties(0).total_memory / 1024**3
        
        print(f"🧠 Current GPU Memory:")
        print(f"   - Allocated: {memory_allocated:.2f} GB")
        print(f"   - Reserved: {memory_reserved:.2f} GB") 
        print(f"   - Total: {memory_total:.2f} GB")
        print(f"   - Free: {memory_total - memory_reserved:.2f} GB")
        
    except Exception as e:
        print(f"❌ CUDA cleanup failed: {e}")
        print("💡 You may need to restart the kernel")

print("🔄 Memory cleanup completed!")

🚨 Emergency memory cleanup...
✅ Deleted model_checkpoint
✅ Deleted trainer_checkpoint
✅ Deleted tokenized_train_checkpoint
✅ Deleted tokenized_dev_checkpoint
🗑️ Garbage collection completed
❌ CUDA cleanup failed: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

💡 You may need to restart the kernel
🔄 Memory cleanup completed!

## 🔄 KERNEL RESTART REQUIRED

**CUDA Out of Memory detected!** 

The GPU memory is completely exhausted. Please **restart the notebook kernel** and then run the cells below to resume training with ultra memory optimization.

**Steps:**
1. **Restart kernel**: `Kernel > Restart` or `Ctrl+Shift+P > Python: Restart`
2. **Run the checkpoint loading cell** (cell that loads `model_checkpoint`)
3. **Run the ultra-optimized training cells** below

This will start fresh with maximum memory efficiency.

In [1]:
# 🚀 FRESH START: Ultra Memory-Optimized Training Setup
import os
import json
import gc
import warnings
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from tqdm.auto import tqdm

import transformers
from transformers import (
    MT5ForConditionalGeneration,
    MT5Tokenizer,
    Seq2SeqTrainer,
    Seq2SeqTrainingArguments,
    DataCollatorForSeq2Seq,
    EarlyStoppingCallback,
    set_seed,
)
from transformers.trainer_utils import EvalPrediction
from datasets import Dataset

warnings.filterwarnings('ignore')
SEED = 42
set_seed(SEED)

print(f'PyTorch: {torch.__version__}')
print(f'Transformers: {transformers.__version__}')
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('CUDA available:', torch.cuda.is_available())
if torch.cuda.is_available():
    print('GPU:', torch.cuda.get_device_name(0))
    print('GPU Memory (GB):', round(torch.cuda.get_device_properties(0).total_memory / 1024**3, 2))

# Ultra-optimized configuration for 8GB GPU
CONFIG: Dict = {
    'model_name': 'google/mt5-small',
    'max_input_length': 96,  # Reduced from 128
    'max_target_length': 96,  # Reduced from 128
    'device': 'cuda' if torch.cuda.is_available() else 'cpu',
    'train_file': 'train.csv',
    'dev_file': 'dev.csv',
    'test_size': 0.1,
    'random_seed': SEED,
    'output_dir': './mt5-hindi-gec-model-fixed',
    'num_train_epochs': 35,
    'per_device_train_batch_size': 1,  # Ultra-small
    'per_device_eval_batch_size': 1,   # Ultra-small
    'gradient_accumulation_steps': 16, # Maintain effective batch size
    'learning_rate': 5e-4,
    'warmup_ratio': 0.1,
    'weight_decay': 0.01,
    'max_grad_norm': 1.0,
    'fp16': True,  # Essential for memory
    'gradient_checkpointing': True,
    'optim': 'adafactor',
    'evaluation_strategy': 'epoch',
    'save_strategy': 'epoch',
    'logging_steps': 50,
    'save_total_limit': 1,  # Keep only 1 checkpoint
    'load_best_model_at_end': True,
    'metric_for_best_model': 'gleu',
    'greater_is_better': True,
    'early_stopping_patience': 4,
    'generation_config': {
        'max_length': 96,  # Reduced
        'num_beams': 2,    # Reduced from 4
        'early_stopping': True,
        'repetition_penalty': 1.2,
        'no_repeat_ngram_size': 3,
        'length_penalty': 1.0,
        'do_sample': False,
    }
}

print("🔧 Ultra Memory-Optimized Configuration Loaded:")
print(f"   - Sequence length: {CONFIG['max_input_length']}")
print(f"   - Batch size: {CONFIG['per_device_train_batch_size']} × {CONFIG['gradient_accumulation_steps']} = {CONFIG['per_device_train_batch_size'] * CONFIG['gradient_accumulation_steps']}")
print(f"   - FP16: {CONFIG['fp16']}")
print(f"   - Generation beams: {CONFIG['generation_config']['num_beams']}")
print("✅ Ready for ultra-optimized training!")

d:\padhai\gaurav nlp\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

PyTorch: 2.8.0+cu129
Transformers: 4.57.0
CUDA available: True
GPU: NVIDIA GeForce RTX 4060 Laptop GPU
GPU Memory (GB): 8.0
🔧 Ultra Memory-Optimized Configuration Loaded:
   - Sequence length: 96
   - Batch size: 1 × 16 = 16
   - FP16: True
   - Generation beams: 2
✅ Ready for ultra-optimized training!

In [2]:
# 🔍 Load Data and Find Latest Checkpoint
def clean_text(text: str) -> str:
    if pd.isna(text):
        return ''
    text = str(text).strip()
    text = ' '.join(text.split())
    text = ''.join(ch for ch in text if ord(ch) >= 32 or ch == '\n')
    return text

# Load data quickly
train_df = pd.read_csv(CONFIG['train_file'], encoding='utf-8')
dev_df = pd.read_csv(CONFIG['dev_file'], encoding='utf-8')

# Process data
if 'input' in train_df.columns and 'output' in train_df.columns:
    train_df = train_df[['input', 'output']].copy()
    dev_df = dev_df[['input', 'output']].copy()
else:
    train_df = train_df[[train_df.columns[0], train_df.columns[1]]].copy()
    dev_df = dev_df[[dev_df.columns[0], dev_df.columns[1]]].copy()

train_df.columns = ['input_text', 'output_text']
dev_df.columns = ['input_text', 'output_text']

train_df['input_text'] = train_df['input_text'].apply(clean_text)
train_df['output_text'] = train_df['output_text'].apply(clean_text)
dev_df['input_text'] = dev_df['input_text'].apply(clean_text)
dev_df['output_text'] = dev_df['output_text'].apply(clean_text)

# Add identity pairs for training
identity_pairs = []
for _, row in dev_df.iterrows():
    identity_pairs.append({
        'input_text': row['output_text'],
        'output_text': row['output_text']
    })

identity_df = pd.DataFrame(identity_pairs)
train_df = pd.concat([train_df, identity_df], ignore_index=True)

print(f"📊 Data loaded: {len(train_df)} train, {len(dev_df)} dev")

# Find latest checkpoint
checkpoint_dir = CONFIG['output_dir']
checkpoints = [d for d in os.listdir(checkpoint_dir) if d.startswith('checkpoint-')]
checkpoints.sort(key=lambda x: int(x.split('-')[1]))

if checkpoints:
    latest_checkpoint = os.path.join(checkpoint_dir, checkpoints[-1])
    print(f"📂 Latest checkpoint: {latest_checkpoint}")
else:
    print("❌ No checkpoints found!")
    latest_checkpoint = None

📊 Data loaded: 13866 train, 107 dev
📂 Latest checkpoint: ./mt5-hindi-gec-model-fixed\checkpoint-6069

In [3]:
# 🚀 Load Ultra-Optimized Model and Tokenizer from Checkpoint
if latest_checkpoint:
    print(f"🔥 Loading ultra-optimized model from: {latest_checkpoint}")
    
    # Load tokenizer and model with memory optimization
    tokenizer = MT5Tokenizer.from_pretrained(latest_checkpoint)
    model = MT5ForConditionalGeneration.from_pretrained(
        latest_checkpoint,
        torch_dtype=torch.float16,  # Force FP16
    )
    
    # Enable gradient checkpointing
    model.gradient_checkpointing_enable()
    model.config.use_cache = False
    
    # Move to device
    model = model.to(CONFIG['device'])
    
    print(f"✅ Model loaded successfully")
    print(f"📊 Parameters: {sum(p.numel() for p in model.parameters()) / 1e6:.1f}M")
    
    if torch.cuda.is_available():
        memory_allocated = torch.cuda.memory_allocated() / 1024**3
        memory_total = torch.cuda.get_device_properties(0).total_memory / 1024**3
        print(f"🧠 GPU Memory: {memory_allocated:.2f} / {memory_total:.2f} GB")
    
else:
    print("❌ No checkpoint found - cannot proceed!")
    model, tokenizer = None, None

🔥 Loading ultra-optimized model from: ./mt5-hindi-gec-model-fixed\checkpoint-6069

`torch_dtype` is deprecated! Use `dtype` instead!

✅ Model loaded successfully
📊 Parameters: 300.2M
🧠 GPU Memory: 0.57 / 8.00 GB

In [4]:
# 🔄 Ultra-Optimized Tokenization with Shorter Sequences
if model is not None and tokenizer is not None:
    print("🔄 Creating ultra-optimized tokenized datasets...")
    
    def create_ultra_tokenization_function(tokenizer, config):
        def tokenize_function(examples):
            inputs = ['grammar correction: ' + text for text in examples['input_text']]
            targets = examples['output_text']
            
            model_inputs = tokenizer(
                inputs,
                max_length=config['max_input_length'],  # 96
                truncation=True,
                padding=False,
            )
            labels = tokenizer(
                text_target=targets,
                max_length=config['max_target_length'],  # 96
                truncation=True,
                padding=False,
            )
            model_inputs['labels'] = labels['input_ids']
            return model_inputs
        return tokenize_function
    
    # Create tokenization function
    tokenize_function = create_ultra_tokenization_function(tokenizer, CONFIG)
    
    # Convert to HF datasets
    hf_train = Dataset.from_pandas(train_df)
    hf_dev = Dataset.from_pandas(dev_df)
    
    # Tokenize with ultra optimization
    tokenized_train = hf_train.map(
        tokenize_function,
        batched=True,
        remove_columns=hf_train.column_names,
        desc='Ultra-optimized tokenization (train)'
    )
    tokenized_dev = hf_dev.map(
        tokenize_function,
        batched=True,
        remove_columns=hf_dev.column_names,
        desc='Ultra-optimized tokenization (dev)'
    )
    
    print(f"✅ Tokenized: {len(tokenized_train)} train, {len(tokenized_dev)} dev")
    
    # Create ultra-optimized data collator
    data_collator = DataCollatorForSeq2Seq(
        tokenizer=tokenizer,
        model=model,
        padding=True,
        max_length=CONFIG['max_input_length'],  # 96
        pad_to_multiple_of=8,
    )
    
    print("✅ Ultra-optimized data collator created")
    
else:
    print("❌ Cannot tokenize - model not loaded!")

🔄 Creating ultra-optimized tokenized datasets...

Ultra-optimized tokenization (train): 100%|██████████| 13866/13866 [00:02<00:00, 6810.49 examples/s]
Ultra-optimized tokenization (dev): 100%|██████████| 107/107 [00:00<00:00, 5755.50 examples/s]
Ultra-optimized tokenization (dev): 100%|██████████| 107/107 [00:00<00:00, 5755.50 examples/s]

✅ Tokenized: 13866 train, 107 dev
✅ Ultra-optimized data collator created

In [5]:
# 📊 Ultra-Optimized Metrics Function
def compute_metrics_ultra(eval_preds: EvalPrediction):
    if isinstance(eval_preds, tuple):
        predictions, labels = eval_preds
    else:
        predictions, labels = eval_preds.predictions, eval_preds.label_ids
    
    if isinstance(predictions, tuple):
        predictions = predictions[0]

    preds = np.array(predictions)
    if preds.ndim == 3:
        preds = preds.argmax(-1)
    preds = preds.astype(np.int64, copy=False)
    
    vocab_size = len(tokenizer)
    preds = np.where((preds >= 0) & (preds < vocab_size), preds, tokenizer.pad_token_id)

    decoded_preds = tokenizer.batch_decode(preds, skip_special_tokens=True)
    labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
    decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)

    decoded_preds = [p.strip() for p in decoded_preds]
    decoded_labels = [l.strip() for l in decoded_labels]

    gleu_scores = []
    for pred, ref in zip(decoded_preds, decoded_labels):
        pt = set(pred.lower().split())
        rt = set(ref.lower().split())
        if not rt:
            gleu_scores.append(0.0)
            continue
        overlap = pt & rt
        precision = len(overlap) / len(pt) if pt else 0.0
        recall = len(overlap) / len(rt)
        f1 = 2 * precision * recall / (precision + recall) if (precision + recall) else 0.0
        gleu_scores.append(f1)
    gleu = float(np.mean(gleu_scores) * 100)

    return {'gleu': gleu}

print("✅ Ultra-optimized metrics function ready")

✅ Ultra-optimized metrics function ready

In [6]:
# 🎯 START ULTRA-OPTIMIZED TRAINING
if model is not None and tokenizer is not None and latest_checkpoint:
    print("=" * 80)
    print("🚀 STARTING ULTRA MEMORY-OPTIMIZED TRAINING")
    print("=" * 80)
    print(f"📂 Resuming from: {latest_checkpoint}")
    print(f"📊 Configuration:")
    print(f"   - Batch size: {CONFIG['per_device_train_batch_size']} × {CONFIG['gradient_accumulation_steps']} = {CONFIG['per_device_train_batch_size'] * CONFIG['gradient_accumulation_steps']}")
    print(f"   - Sequence length: {CONFIG['max_input_length']}")
    print(f"   - FP16: {CONFIG['fp16']}")
    print(f"   - Generation beams: {CONFIG['generation_config']['num_beams']}")
    print("=" * 80)
    
    # Create ultra-optimized training arguments
    training_args = Seq2SeqTrainingArguments(
        output_dir=CONFIG['output_dir'],
        num_train_epochs=CONFIG['num_train_epochs'],
        per_device_train_batch_size=CONFIG['per_device_train_batch_size'],  # 1
        per_device_eval_batch_size=CONFIG['per_device_eval_batch_size'],    # 1
        gradient_accumulation_steps=CONFIG['gradient_accumulation_steps'],  # 16
        learning_rate=CONFIG['learning_rate'],
        warmup_ratio=CONFIG['warmup_ratio'],
        weight_decay=CONFIG['weight_decay'],
        max_grad_norm=CONFIG['max_grad_norm'],
        fp16=CONFIG['fp16'],  # True
        optim=CONFIG['optim'],
        eval_strategy=CONFIG['evaluation_strategy'],
        save_strategy=CONFIG['save_strategy'],
        logging_steps=CONFIG['logging_steps'],
        save_total_limit=CONFIG['save_total_limit'],  # 1
        load_best_model_at_end=CONFIG['load_best_model_at_end'],
        metric_for_best_model=CONFIG['metric_for_best_model'],
        greater_is_better=CONFIG['greater_is_better'],
        predict_with_generate=True,
        generation_max_length=CONFIG['generation_config']['max_length'],  # 96
        generation_num_beams=CONFIG['generation_config']['num_beams'],    # 2
        dataloader_pin_memory=False,
        remove_unused_columns=True,
        report_to='none',
        push_to_hub=False,
        seed=CONFIG['random_seed'],
        dataloader_num_workers=0,
        eval_accumulation_steps=1,
        gradient_checkpointing=CONFIG['gradient_checkpointing'],  # True
        ignore_data_skip=True,
    )
    
    # Create ultra-optimized trainer
    trainer = Seq2SeqTrainer(
        model=model,
        args=training_args,
        data_collator=data_collator,
        train_dataset=tokenized_train,
        eval_dataset=tokenized_dev,
        tokenizer=tokenizer,
        compute_metrics=compute_metrics_ultra,
        callbacks=[EarlyStoppingCallback(early_stopping_patience=CONFIG['early_stopping_patience'])],
    )
    
    print("✅ Ultra-optimized trainer ready!")
    
    # Check memory before training
    if torch.cuda.is_available():
        memory_allocated = torch.cuda.memory_allocated() / 1024**3
        memory_total = torch.cuda.get_device_properties(0).total_memory / 1024**3
        print(f"🧠 GPU Memory before training: {memory_allocated:.2f} / {memory_total:.2f} GB")
    
    try:
        print("🚀 Starting ultra-optimized training...")
        training_result = trainer.train(resume_from_checkpoint=latest_checkpoint)
        
        print("\n" + "=" * 80)
        print("🎉 TRAINING COMPLETED SUCCESSFULLY!")
        print("=" * 80)
        
        # Save final model
        trainer.save_model(CONFIG['output_dir'])
        tokenizer.save_pretrained(CONFIG['output_dir'])
        
        with open(os.path.join(CONFIG['output_dir'], 'training_config_ultra.json'), 'w') as f:
            json.dump(CONFIG, f, indent=2)
        
        print(f"✅ Model saved to: {CONFIG['output_dir']}")
        print("🎉 Ultra-optimized training completed!")
        
    except Exception as e:
        print(f"❌ Training failed: {e}")
        import traceback
        traceback.print_exc()
        
        if "out of memory" in str(e).lower():
            print("\n💡 Still getting CUDA OOM. Final options:")
            print("   - Restart kernel and try with sequence length 64")
            print("   - Use gradient_accumulation_steps=32")
            print("   - Consider using a smaller model or LoRA fine-tuning")
        
else:
    print("❌ Cannot start training - model/checkpoint not loaded!")
    print("💡 Please restart kernel and run the setup cells first.")

================================================================================
🚀 STARTING ULTRA MEMORY-OPTIMIZED TRAINING
================================================================================
📂 Resuming from: ./mt5-hindi-gec-model-fixed\checkpoint-6069
📊 Configuration:
   - Batch size: 1 × 16 = 16
   - Sequence length: 96
   - FP16: True
   - Generation beams: 2
================================================================================
✅ Ultra-optimized trainer ready!
🧠 GPU Memory before training: 0.57 / 8.00 GB
🚀 Starting ultra-optimized training...

There were missing keys in the checkpoint model loaded: ['encoder.embed_tokens.weight', 'decoder.embed_tokens.weight'].
Warning: The following arguments do not match the ones in the `trainer_state.json` within the checkpoint directory:
	per_device_train_batch_size: 1 (from args) != 4 (from trainer_state.json)
Warning: The following arguments do not match the ones in the `trainer_state.json` within the checkpoint directory:
	per_device_train_batch_size: 1 (from args) != 4 (from trainer_state.json)

❌ Training failed: Attempting to unscale FP16 gradients.

Traceback (most recent call last):
  File "C:\Users\Rushang\AppData\Local\Temp\ipykernel_13172\1905173006.py", line 70, in <module>
    training_result = trainer.train(resume_from_checkpoint=latest_checkpoint)
  File "d:\padhai\gaurav nlp\.venv\Lib\site-packages\transformers\trainer.py", line 2325, in train
    return inner_training_loop(
        args=args,
    ...<2 lines>...
        ignore_keys_for_eval=ignore_keys_for_eval,
    )
  File "d:\padhai\gaurav nlp\.venv\Lib\site-packages\transformers\trainer.py", line 2715, in _inner_training_loop
    _grad_norm = self.accelerator.clip_grad_norm_(
        model.parameters(),
        args.max_grad_norm,
    )
  File "d:\padhai\gaurav nlp\.venv\Lib\site-packages\accelerate\accelerator.py", line 2890, in clip_grad_norm_
    self.unscale_gradients()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "d:\padhai\gaurav nlp\.venv\Lib\site-packages\accelerate\accelerator.py", line 2828, in unscale_gradients
    self.scaler.unscale_(opt)
    ~~~~~~~~~~~~~~~~~~~~^^^^^
  File "d:\padhai\gaurav nlp\.venv\Lib\site-packages\torch\amp\grad_scaler.py", line 346, in unscale_
    optimizer_state["found_inf_per_device"] = self._unscale_grads_(
                                              ~~~~~~~~~~~~~~~~~~~~^
        optimizer, inv_scale, found_inf, False
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "d:\padhai\gaurav nlp\.venv\Lib\site-packages\torch\amp\grad_scaler.py", line 264, in _unscale_grads_
    raise ValueError("Attempting to unscale FP16 gradients.")
ValueError: Attempting to unscale FP16 gradients.

In [7]:
# 🔧 FIX FP16 GRADIENT ISSUE - START ULTRA-OPTIMIZED TRAINING (FIXED)
if model is not None and tokenizer is not None and latest_checkpoint:
    print("=" * 80)
    print("🚀 STARTING ULTRA MEMORY-OPTIMIZED TRAINING (FP16 FIXED)")
    print("=" * 80)
    print(f"📂 Resuming from: {latest_checkpoint}")
    print(f"📊 Configuration:")
    print(f"   - Batch size: {CONFIG['per_device_train_batch_size']} × {CONFIG['gradient_accumulation_steps']} = {CONFIG['per_device_train_batch_size'] * CONFIG['gradient_accumulation_steps']}")
    print(f"   - Sequence length: {CONFIG['max_input_length']}")
    print(f"   - FP16: {CONFIG['fp16']}")
    print(f"   - Generation beams: {CONFIG['generation_config']['num_beams']}")
    print("=" * 80)
    
    # Load model in FP32 and convert to FP16 properly
    model = model.float()  # Ensure model is in FP32 first
    
    # Create ultra-optimized training arguments with FP16 fix
    training_args = Seq2SeqTrainingArguments(
        output_dir=CONFIG['output_dir'],
        num_train_epochs=CONFIG['num_train_epochs'],
        per_device_train_batch_size=CONFIG['per_device_train_batch_size'],  # 1
        per_device_eval_batch_size=CONFIG['per_device_eval_batch_size'],    # 1
        gradient_accumulation_steps=CONFIG['gradient_accumulation_steps'],  # 16
        learning_rate=CONFIG['learning_rate'],
        warmup_ratio=CONFIG['warmup_ratio'],
        weight_decay=CONFIG['weight_decay'],
        max_grad_norm=CONFIG['max_grad_norm'],
        fp16=True,  # Enable FP16
        fp16_opt_level="O1",  # Use O1 optimization level for better stability
        fp16_backend="auto",  # Let transformers choose the best backend
        optim=CONFIG['optim'],
        eval_strategy=CONFIG['evaluation_strategy'],
        save_strategy=CONFIG['save_strategy'],
        logging_steps=CONFIG['logging_steps'],
        save_total_limit=CONFIG['save_total_limit'],  # 1
        load_best_model_at_end=CONFIG['load_best_model_at_end'],
        metric_for_best_model=CONFIG['metric_for_best_model'],
        greater_is_better=CONFIG['greater_is_better'],
        predict_with_generate=True,
        generation_max_length=CONFIG['generation_config']['max_length'],  # 96
        generation_num_beams=CONFIG['generation_config']['num_beams'],    # 2
        dataloader_pin_memory=False,
        remove_unused_columns=True,
        report_to='none',
        push_to_hub=False,
        seed=CONFIG['random_seed'],
        dataloader_num_workers=0,
        eval_accumulation_steps=1,
        gradient_checkpointing=CONFIG['gradient_checkpointing'],  # True
        ignore_data_skip=True,
        # Additional stability settings
        skip_memory_metrics=True,
        log_level="warning",  # Reduce logging
    )
    
    # Create ultra-optimized trainer
    trainer = Seq2SeqTrainer(
        model=model,
        args=training_args,
        data_collator=data_collator,
        train_dataset=tokenized_train,
        eval_dataset=tokenized_dev,
        tokenizer=tokenizer,
        compute_metrics=compute_metrics_ultra,
        callbacks=[EarlyStoppingCallback(early_stopping_patience=CONFIG['early_stopping_patience'])],
    )
    
    print("✅ Ultra-optimized trainer ready (FP16 fixed)!")
    
    # Check memory before training
    if torch.cuda.is_available():
        memory_allocated = torch.cuda.memory_allocated() / 1024**3
        memory_total = torch.cuda.get_device_properties(0).total_memory / 1024**3
        print(f"🧠 GPU Memory before training: {memory_allocated:.2f} / {memory_total:.2f} GB")
    
    try:
        print("🚀 Starting ultra-optimized training with FP16 fix...")
        training_result = trainer.train(resume_from_checkpoint=latest_checkpoint)
        
        print("\n" + "=" * 80)
        print("🎉 TRAINING COMPLETED SUCCESSFULLY!")
        print("=" * 80)
        
        # Save final model
        trainer.save_model(CONFIG['output_dir'])
        tokenizer.save_pretrained(CONFIG['output_dir'])
        
        with open(os.path.join(CONFIG['output_dir'], 'training_config_ultra.json'), 'w') as f:
            json.dump(CONFIG, f, indent=2)
        
        print(f"✅ Model saved to: {CONFIG['output_dir']}")
        print("🎉 Ultra-optimized training completed!")
        
    except Exception as e:
        print(f"❌ Training failed: {e}")
        import traceback
        traceback.print_exc()
        
        if "out of memory" in str(e).lower():
            print("\n💡 Still getting CUDA OOM. Final options:")
            print("   - Try disabling FP16 (use FP32)")
            print("   - Reduce sequence length to 64")
            print("   - Use gradient_accumulation_steps=32")
            print("   - Consider using a smaller model or LoRA fine-tuning")
        
else:
    print("❌ Cannot start training - model/checkpoint not loaded!")
    print("💡 Please restart kernel and run the setup cells first.")

================================================================================
🚀 STARTING ULTRA MEMORY-OPTIMIZED TRAINING (FP16 FIXED)
================================================================================
📂 Resuming from: ./mt5-hindi-gec-model-fixed\checkpoint-6069
📊 Configuration:
   - Batch size: 1 × 16 = 16
   - Sequence length: 96
   - FP16: True
   - Generation beams: 2
================================================================================
✅ Ultra-optimized trainer ready (FP16 fixed)!
🧠 GPU Memory before training: 2.25 / 8.00 GB
🚀 Starting ultra-optimized training with FP16 fix...

There were missing keys in the checkpoint model loaded: ['encoder.embed_tokens.weight', 'decoder.embed_tokens.weight'].

KeyboardInterrupt:

## 7. Inference — generate predictions and save CSV - FIXED

In [16]:
def generate_predictions(model_path: str, test_file: str, output_file: str = 'predictions.csv', batch_size: int = 16):
    print(f'Loading model from {model_path} ...')
    tok = MT5Tokenizer.from_pretrained(model_path)
    mdl = MT5ForConditionalGeneration.from_pretrained(model_path).to(device)
    mdl.eval()

    df = pd.read_csv(test_file, encoding='utf-8')
    if 'input' in df.columns:
        input_col = 'input'
    else:
        input_col = df.columns[0]
    df = df[[input_col]].copy()
    df.columns = ['input_text']
    df['input_text'] = df['input_text'].apply(clean_text)
    df = df[df['input_text'] != '']

    preds: List[str] = []
    with torch.no_grad():
        for i in tqdm(range(0, len(df), batch_size), desc='Generating'):
            batch = df.iloc[i:i+batch_size]
            # ✅ CRITICAL FIX: Use same task prefix as training
            inputs = ['grammar correction: ' + s for s in batch['input_text'].tolist()]
            enc = tok(
                inputs,
                max_length=CONFIG['max_input_length'],
                truncation=True,
                padding=True,
                return_tensors='pt',
            ).to(device)
            outputs = mdl.generate(
                **enc,
                max_length=CONFIG['generation_config']['max_length'],
                num_beams=CONFIG['generation_config']['num_beams'],
                early_stopping=CONFIG['generation_config']['early_stopping'],
                repetition_penalty=CONFIG['generation_config']['repetition_penalty'],
                no_repeat_ngram_size=CONFIG['generation_config']['no_repeat_ngram_size'],
            )
            decoded = tok.batch_decode(outputs, skip_special_tokens=True)
            preds.extend(decoded)
            if torch.cuda.is_available() and i % 100 == 0:
                torch.cuda.empty_cache()
                gc.collect()

    out_df = pd.DataFrame({
        'Input sentence': df['input_text'].tolist()[:len(preds)],
        'Output sentence': preds,
    })
    out_df.to_csv(output_file, index=False, encoding='utf-8')
    print('Predictions saved to', output_file)
    print(out_df.head())
    return out_df

# Generate predictions
_ = generate_predictions(CONFIG['output_dir'], CONFIG['dev_file'], 'predictions_fixed.csv')

Loading model from ./mt5-hindi-gec-model-fixed ...

Generating: 100%|██████████| 7/7 [00:15<00:00,  2.27s/it]

Predictions saved to predictions_fixed.csv
                                      Input sentence  \
0  कहते है 'शिक्षा शेरनी को वो दुध है जिसने जितना...
1  आज-कल की विशेष बात यही है कि शिक्षा पे राजा से...
2    जलवायु परिवर्तन आज के समय की सच्चाई बन चुकी है।
3  आज पूरा विश्व जलवायु परिवर्तन की समस्या से जूझ...
4  सबसे पहले हम जानते हैं कि जलवायु परिवर्तन है क...

                                     Output sentence
0  कहते हैं 'शिक्षा शेरनी को वो दुध है जिसने जितन...
1  आज-कल की विशेष बात यही है कि शिक्षा पे राजा से...
2    जलवायु परिवर्तन आज के समय की सच्चाई बन चुकी है।
3  आज पूरा विश्व जलवायु परिवर्तन की समस्या से जूझ...
4  सबसे पहले हम जानते हैं कि जलवायु परिवर्तन है क...

## 8. Evaluation - Check if fixes worked

In [17]:
def gleu_proxy(preds, refs):
    scores = []
    for pred, ref in zip(preds, refs):
        pt, rt = set(str(pred).lower().split()), set(str(ref).lower().split())
        if not rt:
            scores.append(0.0)
            continue
        overlap = pt & rt
        p = len(overlap) / len(pt) if pt else 0.0
        r = len(overlap) / len(rt)
        f1 = 2 * p * r / (p + r) if (p + r) else 0.0
        scores.append(f1)
    return float(np.mean(scores) * 100)

# Load references
dev_df_eval = pd.read_csv(CONFIG['dev_file'], encoding='utf-8')
in_col = 'input' if 'input' in dev_df_eval.columns else dev_df_eval.columns[0]
ref_col = 'output' if 'output' in dev_df_eval.columns else dev_df_eval.columns[1]
refs = dev_df_eval[ref_col].astype(str).tolist()

# Load model predictions
pred_df = pd.read_csv('predictions_fixed.csv', encoding='utf-8')
preds = pred_df['Output sentence'].astype(str).tolist()

# Compute metrics
gleu_model = gleu_proxy(preds, refs)
gleu_identity = gleu_proxy(dev_df_eval[in_col].astype(str).tolist(), refs)
exact_match = (pd.Series(preds) == pd.Series(refs)).mean() * 100.0

print("🔥 RESULTS AFTER FIXES:")
print(f"Dev GLEU (proxy) — FIXED model: {gleu_model:.2f}")
print(f"Dev GLEU (proxy) — identity baseline: {gleu_identity:.2f}")
print(f"Exact match rate: {exact_match:.2f}%")

# Check for <extra_id_0> tokens
extra_id_count = sum(1 for pred in preds if '<extra_id_0>' in str(pred))
print(f"\n🚨 Sentences with <extra_id_0>: {extra_id_count}/{len(preds)} ({extra_id_count/len(preds)*100:.1f}%)")

if gleu_model > gleu_identity:
    print("\n🎉 SUCCESS! Model is now better than identity baseline!")
else:
    print("\n⚠️  Model still below identity baseline. May need more training or different approach.")

# Show sample results
print("\n📋 Sample results:")
for i in range(min(5, len(pred_df))):
    print(f"{i+1}.")
    print("Input:   ", pred_df.iloc[i]['Input sentence'][:100])
    print("Pred:    ", pred_df.iloc[i]['Output sentence'][:100])
    print("Ref:     ", dev_df_eval.iloc[i][ref_col][:100])
    print()

🔥 RESULTS AFTER FIXES:
Dev GLEU (proxy) — FIXED model: 84.63
Dev GLEU (proxy) — identity baseline: 85.47
Exact match rate: 14.95%

🚨 Sentences with <extra_id_0>: 0/107 (0.0%)

⚠️  Model still below identity baseline. May need more training or different approach.

📋 Sample results:
1.
Input:    कहते है 'शिक्षा शेरनी को वो दुध है जिसने जितना पिया उतना ही दहाडा है'।
Pred:     कहते हैं 'शिक्षा शेरनी को वो दुध है जिसने जितना पिया उतना ही दहाडा है'।
Ref:      कहते है 'शिक्षा शेरनी का वो दूध है जिसने जितना पिया उतना ही दहाड़ा है'।

2.
Input:    आज-कल की विशेष बात यही है कि शिक्षा पे राजा से लेकर रंक का भी अधिकार है।
Pred:     आज-कल की विशेष बात यही है कि शिक्षा पे राजा से लेकर रंक का भी अधिकार है।
Ref:      आज-कल की विशेष बात यही है कि शिक्षा पर राजा से लेकर रंक का भी अधिकार है।

3.
Input:    जलवायु परिवर्तन आज के समय की सच्चाई बन चुकी है।
Pred:     जलवायु परिवर्तन आज के समय की सच्चाई बन चुकी है।
Ref:      जलवायु परिवर्तन आज के समय की सच्चाई बन चुकी है।

4.
Input:    आज पूरा विश्व जलवायु परिवर्तन की समस्या से जूझ रहा है।
Pred:     आज पूरा विश्व जलवायु परिवर्तन की समस्या से जूझ रहा है।
Ref:      आज पूरा विश्व जलवायु परिवर्तन की समस्या से जूझ रहा है।

5.
Input:    सबसे पहले हम जानते हैं कि जलवायु परिवर्तन है क्या?
Pred:     सबसे पहले हम जानते हैं कि जलवायु परिवर्तन है क्या?
Ref:      सबसे पहले हम जानते हैं कि जलवायु परिवर्तन है क्या?

In [18]:
# Calculate GLEU score directly from dev.csv (input vs output)
import pandas as pd

def calculate_gleu_from_csv(csv_file):
    """Calculate GLEU score between input and output columns in CSV"""
    df = pd.read_csv(csv_file, encoding='utf-8')
    
    # Get column names
    if 'Input sentence' in df.columns and 'Output sentence' in df.columns:
        input_col = 'Input sentence'
        output_col = 'Output sentence'
    elif 'input' in df.columns and 'output' in df.columns:
        input_col = 'input'
        output_col = 'output'
    else:
        input_col = df.columns[0]
        output_col = df.columns[1]
    
    print(f"📄 File: {csv_file}")
    print(f"📊 Total sentences: {len(df)}")
    print(f"📝 Input column: '{input_col}'")
    print(f"📝 Output column: '{output_col}'")
    
    # Get inputs and outputs
    inputs = df[input_col].astype(str).tolist()
    outputs = df[output_col].astype(str).tolist()
    
    # Calculate GLEU score using the same function
    gleu_score = gleu_proxy(inputs, outputs)
    
    print(f"\n🎯 GLEU Score (Input → Output): {gleu_score:.2f}")
    
    # Calculate some additional statistics
    exact_matches = sum(1 for inp, out in zip(inputs, outputs) if inp.strip() == out.strip())
    different_count = len(df) - exact_matches
    
    print(f"📈 Exact matches: {exact_matches}/{len(df)} ({exact_matches/len(df)*100:.1f}%)")
    print(f"🔄 Different pairs: {different_count}/{len(df)} ({different_count/len(df)*100:.1f}%)")
    
    # Show some examples of different pairs
    print(f"\n📋 Sample corrections from {csv_file}:")
    different_pairs = [(inp, out) for inp, out in zip(inputs, outputs) if inp.strip() != out.strip()]
    for i, (inp, out) in enumerate(different_pairs[:5], 1):
        print(f"{i}.")
        print(f"  Input:  {inp[:100]}")
        print(f"  Output: {out[:100]}")
        print()
    
    return gleu_score

# Calculate GLEU score from dev.csv
print("🔍 Calculating GLEU score directly from dev.csv file:")
dev_gleu = calculate_gleu_from_csv('dev.csv')

🔍 Calculating GLEU score directly from dev.csv file:
📄 File: dev.csv
📊 Total sentences: 107
📝 Input column: 'Input sentence'
📝 Output column: 'Output sentence'

🎯 GLEU Score (Input → Output): 85.47
📈 Exact matches: 24/107 (22.4%)
🔄 Different pairs: 83/107 (77.6%)

📋 Sample corrections from dev.csv:
1.
  Input:  कहते है 'शिक्षा शेरनी को वो दुध है जिसने जितना पिया उतना ही दहाडा है'।
  Output: कहते है 'शिक्षा शेरनी का वो दूध है जिसने जितना पिया उतना ही दहाड़ा है'।

2.
  Input:  आज-कल की विशेष बात यही है कि शिक्षा पे राजा से लेकर रंक का भी अधिकार है।
  Output: आज-कल की विशेष बात यही है कि शिक्षा पर राजा से लेकर रंक का भी अधिकार है।

3.
  Input:  दरअसल मानवीय गतिविधिया जैसे कि शहरीकरण, औद्योगिकरण इत्यादि के कारण विश्व का तापमान तेजी से बढ़ रहा ह
  Output: दरअसल मानवीय गतिविधियां जैसे कि शहरीकरण, औद्योगीकरण इत्यादि के कारण विश्व का तापमान तेजी से बढ़ रहा

4.
  Input:  वास्तव में हमारी पृथ्वी प्राकृतिक रूप से तापमान की एक चक्र से गुजरती हैं जिसमे पृथ्वी का तापमान एक न
  Output: वास्तव में हमारी पृथ्वी प्राकृतिक रूप से तापमान की एक चक्र से गुजरती है जिसमे पृथ्वी का तापमान एक न्

5.
  Input:  सर्दियाँ भी पहले के मुकाबले ज्यादा कड़ाके की पड़ रही है जिससे प्रभावित होकर कई लोग काल का ग्रास बन रह
  Output: सर्दियाँ भी पहले के मुकाबले ज्यादा कड़ाके की पड़ रही है जिससे प्रभावित होकर कई लोग काल का ग्रास बन रह

In [19]:
# Quick summary of dev.csv GLEU score
print("=" * 50)
print("📊 SUMMARY: GLEU Score from dev.csv")
print("=" * 50)
print(f"🎯 GLEU Score (Input → Output): {dev_gleu:.2f}")
print("=" * 50)

==================================================
📊 SUMMARY: GLEU Score from dev.csv
==================================================
🎯 GLEU Score (Input → Output): 85.47
==================================================